### ISSUE TITLE
I don't know how to compile it yet. What configuration is needed? Cmake compilation prompt is missing opencasacde, vtk, etc.

### ISSUE THREAD

**Issue by XXMCUG** [LaughlinResearch/SMESH#17]
I don't know how to compile it yet. What configuration is needed? Cmake compilation prompt is missing opencasacde, vtk, etc.

**Comment by trelau** [comment]
can you provide more information about what errors you are getting? if you're familiar with Anaconda you might try and install the pre-built SMESH from conda-forge https://anaconda.org/conda-forge/smesh

**Comment by XXMCUG** [comment]
> 您能否提供有关所遇到的错误的更多信息？如果您熟悉Anaconda，则可以尝试从conda-forge https://anaconda.org/conda-forge/smesh安装预构建的SMESH[](https://anaconda.org/conda-forge/smesh)

Hello, I downloaded your SALOME source code, and I used cmake to compile. After I clicked on config, I was prompted that some libraries are missing. Can't your project be compiled with cmake? Or do some libraries that I need to configure myself? Thank you

Here are my tips for compiling with cmake3.12:
########################################
CMake Error at CMakeLists.txt:37 (find_package):
  By not providing "FindOpenCASCADE.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "OpenCASCADE", but CMake did not find one.

  Could not find a package configuration file provided by "OpenCASCADE" with
  any of the following names:

    OpenCASCADEConfig.cmake
    opencascade-config.cmake

  Add the installation prefix of "OpenCASCADE" to CMAKE_PREFIX_PATH or set
  "OpenCASCADE_DIR" to a directory containing one of the above files.  If
  "OpenCASCADE" provides a separate development package or SDK, be sure it
  has been installed.
########################################

**Comment by trelau** [comment]
if you are using a conda environment, try installing OpenCASCADE (and other dependencies) with something like ```conda install -c conda-forge occt```. In fact, if you are using conda then you can likely install smesh via ```conda install -c conda-forge smesh```.

If you are not using conda, then you will need to provide the dependencies manually, such as paths to include and library directories

**Comment by XXMCUG** [comment]
> if you are using a conda environment, try installing OpenCASCADE (and other dependencies) with something like `conda install -c conda-forge occt`. In fact, if you are using conda then you can likely install smesh via `conda install -c conda-forge smesh`.
> 
> If you are not using conda, then you will need to provide the dependencies manually, such as paths to include and library directories

I  understand, thank you for your guidance !

**Comment by trelau** [comment]
ok great. i'll go ahead and close the issue then.

**Comment by weiweiisok** [comment]
I have install smesh via 'conda install -c conda-forge smesh', but I still can't import smesh module, and I also find that the file library of smesh only have two files named 'info' and 'Library', It's not a python file?

**Comment by trelau** [comment]
@weiweiisok if you're looking for python bindings try https://github.com/trelau/pySMESH. this repo is the c++ library

**Comment by muezabdalla** [comment]
hi 
I am beginner to compiling.
I am facing the same problem but i want to compile smesh without conda. I downloaded the source core of occt and tried to put it it src and external but did not work. i also tried to search for the variable CMAKE_MODULE_PATH in the file CMakeLists.txt but did not find it.
i am using void linux and I was facing a lot of problems when tried to use salome so I thought that I can compile smesh because I only need smesh and geometry modules  in salome.
